# Module

# Giới thiệu

Module là một cách tổ chức code trong python. Module là một file với đuôi là `.py`.

# Công dụng
Module là tập hợp các đối tượng, hàm, ... với một chức năng nào đó.

Ví dụ : trong một game, chúng ta có thể có module để xử lý logic, module để xử lý hình ảnh, ...

## Cách sử dụng module
Để sử dụng module, chúng ta cần phải khai báo nó như sau : 
```
import <tên_module>
```

In [ ]:
import random

Thông thường, việc khai báo này thường được đặt ở đầu chương trình để quản lý. Tuy nhiên, bạn có khai báo module tại bất cứ đâu, miễn là trước khi sử dụng nó.

Bạn có thể đặt lại tên cho module mình khai báo bằng cách dùng từ khóa `as` như sau :
```
import <tên_module> as <tên_đặt_lại>
```

In [1]:
import random as rd
import numpy as np
import pandas as pd

Sau khi đã khai báo, bạn có thể sử dụng các đối tượng, hàm, ... trong module bằng cách sau :
```
<tên_module>.<tên_đối_tượng_cần_dùng>
```

In [2]:
rd.randint(0, 10)

6

Đôi khi, bạn chỉ muốn sử dụng một hàm, đối tượng, ... nào đó của module, bạn có thể khai báo bằng cách
```
from <tên_module> import <tên_đối_tượng>
```
Lúc đó, bạn có thể dùng trực tiếp `tên_đối_tượng` mà không cần thông qua `tên_module`

In [3]:
# chỉ dùng hàm randint trong module random
from random import randint

randint(1, 10)

10

In [4]:
# bạn cũng có thể dùng 'as' để đặt lại tên
from random import randrange as rr

rr(1, 10)

1

## Package
Ngoài ra, python còn một cách tổ chức code nữa là package. Về cơ bản, package là một thư mục (folder), trong đó có thể chứa các thư mục con (sub-package) hoặc các file `.py` (module). 

Thông thường, bạn sẽ khai báo một (hoặc nhiều) module từ package như sau :
1. `import <tên_package>.<tên_module> [as <tên_đặt_lại>]`
2. `from <tên_package> import <tên_module> [as <tên_đặt_lại>]`

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
from matplotlib import pyplot as plt

## Một số package
Python có rất nhiều package cho các mục đích khác nhau, một số ví dụ như :
- Phân tích dữ liệu : `numpy`, `pandas`, ...
- Trực quan hóa dữ liệu (data visualization) : `matplotlib`, `seaborn`, ...
- Trí tuệ nhân tạo (AI) : `scikit-learn`, `tensorflow`, `keras`, `nltk`, ...
- Lập trình web : `django`, `flask`, ...
- Lập trình game : `pygame`, `pyglet`, ...
- ...


# Module `numpy`

## Giới thiệu
Module `numpy` là một module phục vụ cho khoa học máy tính của Python, hỗ trợ cho việc tính toán các mảng nhiều chiều, có kích thước lớn với các hàm đã được tối ưu áp dụng lên các mảng nhiều chiều đó. `numpy` đặc biệt hữu ích khi thực hiện các hàm liên quan tới Đại số tuyến tính (véc-tơ, ma trận, ...).

In [1]:
# muốn sử dụng numpy, trước tiên là phải khai báo
import numpy as np

np

<module 'numpy' from '/usr/lib/python3/dist-packages/numpy/__init__.py'>

## Kiểu dữ liệu `ndarray` (mảng nhiều chiều)
Là kiểu dữ liệu đặc trưng của `numpy`, có thể xem như dạng `list` đặc biệt. Để tạo ra một `ndarray`, bạn dùng hàm `np.array`.

In [ ]:
# tạo ndarray 1 chiều
a = np.array([1, 2, 3])

print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [2]:
# tạo ndarray 2 chiều
import numpy as np
data = [[1, 2, 3], [4, 5, 6]]
b = np.array(data)

print(data)
print(b)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


Nói một cách đơn giản, `ndarray` 1 chiều là vector, `ndarray` 2 chiều là ma trận.

Tương tự, bạn có thể tạo ra các mảng 3 chiều, 4 chiều, ...

## `np.arange()`
`np.arange()` là một hàm tương tự với hàm `range()` của python, tuy nhiên, `np.arange()` cho phép người dùng sử dụng bước nhảy là số bất kỳ, trong khi `range()` chỉ cho phép bước nhảy là số nguyên.

In [10]:
np.arange(1, 2, 0.5)

array([1. , 1.5])

In [11]:
for i in np.arange(1, 5, 0.75):
    print(i)

1.0
1.75
2.5
3.25
4.0
4.75


# Truy xuất thông tin về một `ndarray`
Bạn có thể truy xuất một sô thông tin về `ndarray` như sau :
- `<tên_array>.dtype` sẽ trả về kiểu dữ liệu các phần tử (khác với `list`, các phần tử trong `ndarray` có cùng kiểu.
- `<tên_array>.shape` sẽ trả về kích thước của `ndarray`.

In [18]:
import numpy as np
a = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
b = np.array([2, 5, 8])

print(a.shape)
print(b.shape)

(2, 4)
(3,)


In [ ]:
print(b.dtype)
print(b.shape)

int64
(2, 3)


## Truy xuất phần tử của `ndarray`

Đối với `ndarray` một chiều, bạn có thể dùng cách truy xuất của `list`.
![Fig1](https://numpy.org/doc/stable/_images/np_indexing.png)

In [ ]:
print(a[0])
print(a[0:2])
print(a[-1])

1
[1 2]
3


Đối với `ndarray` 2 chiều, bạn có thể dùng cách sau :
```
<tên_array>[<dòng_muốn_lấy>, <cột_muốn_lấy>]
```

![fig2](https://numpy.org/doc/stable/_images/np_matrix_indexing.png)

In [11]:
data = [[1, 2, 3], [4, 5, 6]]
b = np.array(data)

print(data[0][0])
print(b[0, 0])

1
1


Đối với `ndarray` 3 chiều trở lên, bạn thực hiện tương tự như `ndarray` 2 chiều.

## Lọc theo điều kiện
Ngoài ra, bạn có thể lấy ra các phần tử trong `ndarray` thỏa một điều kiện nào đó bằng cách
```
<tên_array>[điều_kiện]
``` 

In [18]:
b = np.array([[1, 2, 3], [4, 5, 6]])
# Lấy ra các phần tử chia hết cho 2 ở trong b
b[~(b % 2 == 0)]

array([1, 3, 5])

Bạn có thể viết điều kiện phức tạp với một lưu ý phải dùng các ký hiệu khác cho các phép toán logic :
- Dùng `&` thay cho `and`.
- Dùng `|` thay cho `or`.
- Dùng `~` thay cho `not`.

In [ ]:
# Lấy ra các phần tử chia hết cho 2 và lớn hơn 3 ở trong b
b[(b % 2 == 0) & (b > 3)]

array([4, 6])

## Các phép toán trên `ndarray`

Khi thực hiện các phép toán (cộng, trừ, nhân, chia) hai `ndarray` cùng kích thước, `numpy` sẽ tiến hành phép toán theo từng phần tử một. Đây là điểm cần lưu ý khi thực hiện phép nhân 2 'ma trận' (`ndarray` 2 chiều), vì đó không phải là phép nhân 2 ma trận được định nghĩa trong toán học.

![Minh họa](https://numpy.org/doc/stable/_images/np_sub_mult_divide.png)

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 6, 3])

print(a * b)

[ 4 12  9]


In [5]:
m1 = np.array([[1, 0], [0, 1]])
m2 = np.array([[1, 2], [3, 4]])

print(m1 * m2)

[[1 0]
 [0 4]]


## Broadcasting

Broadcasting là phương pháp numpy dùng để xử lý các phép tính giữa các `ndarray` với kích thước khác nhau.

Cùng xem một số ví dụ sau đây.

In [2]:
# tinh toán giữa ndarray 1 chiều và một số
a = np.array([1, 2, 3])
b = 2

print(a + b) # = [1+2, 2+2, 3+2]

[3 4 5]


In [3]:
# tinh toán giữa ndarray 2 chiều và một số
a = np.array([[1, 2, 3], [4, 5, 6]])
b = -2

print(a + b) # = [[1-2, 2-2, 3-2], [4-2, 5-2, 6-2]]

[[-1  0  1]
 [ 2  3  4]]


In [20]:
# tinh toán giữa ndarray 2 chiều và ndarray 1 chiều
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[5], [10]])
c = np.array([1, 2, 3])

print(a * b)
print(a * c)
print(b * c)

[[ 5 10 15]
 [40 50 60]]
[[ 1  4  9]
 [ 4 10 18]]
[[ 5 10 15]
 [10 20 30]]


### Nguyên tắc chung cho broadcasting

Khi tính toán giữa hai `ndarray`, `numpy` sẽ so sánh **kích thước** giữa chúng theo thứ tự từ phải qua trái.

Một chiều của hai `ndarray` được gọi là tương thích khi:
- Bằng nhau.
- Hoặc có một chiều là 1.

Nếu **tất cả** các chiều đều tương thích thì có thể broadcasting hai `ndarray` khi tính toán.

Ví dụ các trường hợp sau đây là tương thích.
```
Kích thước của a: 255 x 255 x 3
Kích thước của b:             3
```

```
Kích thước của a: 8 x 1 x 6 x 1
Kích thước của b:     7 x 1 x 5
```

Minh họa kết quả broadcasting

![Nhân ndarray một chiều với một số](https://numpy.org/doc/stable/_images/broadcasting_1.png)

In [12]:
a = np.array([1, 2, 3])
print(a * 2)

[2 4 6]


![Cộng một ndarray 2 chiều với một ndarrayy 1 chiều](https://numpy.org/doc/stable/_images/broadcasting_2.png)

In [14]:
a = np.array([[ 0,  0,  0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([1, 2, 3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


![Ví dụ 3](https://numpy.org/doc/stable/_images/broadcasting_4.png)

In [15]:
a = np.array([[ 0],
              [10],
              [20],
              [30]])
b = np.array([1, 2, 3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [17]:
# không thể broadcasting
a = np.array([[1, 2, 3], [3, 4, 5]])
b = np.array([1, 2])
print(a * b)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

## Đại số tuyến tính với `ndarray`

### Tính toán ma trận
`numpy` có một số hàm để thực hiện các phép tính trân ma trận như sau:
- `np.dot()`: nhân ma trận.
- `np.trace()`: tính vết của ma trận.
- `np.transpose()`: tính ma trận chuyển vị.
- `np.linalg.det()`: tính định thức.
- `np.linalg.inv()`: tính ma trận nghịch đảo.

In [6]:
m1 = np.array([[1, 0], [-1, 2]])
m2 = np.array([[-1, 1], [1, -2]])
print(np.dot(m1, m2))
print(np.linalg.det(m1))
print(np.inv(m2))

array([[1, 2],
       [3, 4]])

### Giải hệ phương trình tuyến tính

Để giải hệ phương trình tuyến tính
$$
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\ \vdots\\x_n
\end{bmatrix}
=\begin{bmatrix}
b_1\\b_2\\ \vdots\\b_n
\end{bmatrix}
$$
ta có thể dùng hàm `np.linalg.solve(A, b)` với
$$ A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}
\quad
b
=\begin{bmatrix}
b_1\\b_2\\ \vdots\\b_n
\end{bmatrix}
$$

Ví dụ, bài toán:
```
Vừa gà, vừa chó
Bó lại cho tròn
Ba mươi sáu con
Một trăm chân chẵn
```
tương đương với hệ:
$$
\begin{bmatrix}
1 & 1\\
2 & 4\\
\end{bmatrix}
\begin{bmatrix}
x\\y\\
\end{bmatrix}
=\begin{bmatrix}
36\\100\\
\end{bmatrix}
$$

In [ ]:
A = np.array([[1, 1], [2, 4]])
b = np.array([36, 100])
np.linalg.solve(A, b)